### ISSUE TITLE
Recommend additional install requirements

### ISSUE THREAD

**Issue by michael-myers** [perimosocordiae/picross#1]
I just discovered your project when I checked to see if a Picross OCR existed, before I tried to make one. I think it's cool that you're already working on it.

While installing, I found that maybe these packages are additional requirements:
`matplotlib, scipy, scikit-learn, opencv-python`

And maybe the README could clarify that the `webtool` package is found on your GitHub. I found it, but only after some Googling let me back here.

I was able to successfully run the UI server at that point.

**Comment by perimosocordiae** [comment]
You have good timing! As you can see, this project is pretty new, so I haven't gotten around to documenting things properly yet. This started as a simple little demo of the webtool interface, but it was fun to hack on, so here we are.

I haven't tested the code much except on my machine, so I expect that things won't work perfectly right away. The OCR code is particularly flaky at the moment. Let me know if you ran into issues or if you have ideas for improvement!

**Comment by perimosocordiae** [comment]
Fixed (at least partially) by 4978fca.
